# -*- coding: utf-8 -*-
"""Master Class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uxb6B2mx0nV7yYgLN7UodN2cDhHc6Qjs

VARIABLES
"""

# El número se utiliza para comentar códigos
# La variable es un contenedor de información
# Las variables no pueden empezar con números
# Las variables no pueden llamarse como una palabra predeterminada por Python
# ejemplo: print, for, is, while, etc
a = 5 # tipo de dato entero (int) 4 bites
b = 45.3 # Tipo de dato decimal se llaman flotantes (float) 8bites
print(b) # imprimir por terminal el contenido
# Podemos preguntar que tipo de número es
print(type(b))
# Muestra en la consola que es flotante

c = input("Ingrese su nombre")
# str para cadena de caracteres. string. Hola tiene 4 caracteres
print(c)

c = input("Ingrese su nombre: ")
# str para cadena de caracteres. string. Hola tiene 4 caracteres
# Puedo obligarlo a algo se llama recasting. en este caso entero (int)
d = int(input("Ingrese su edad: "))

# Corregido: Imprime el nombre y la edad usando f-strings para un formato correcto.
print(f"Mi Nombre es: {c}")
print(f"Tengo {d} años")

a = 5 # tipo de dato entero (int) 4 bites
b = 45.3 # Tipo de dato decimal se llaman flotantes (float) 8bites
suma = a + b
resta = a - b
Multiplicacion = a * b
Division = a / b
potencia = a ** b
print(suma)
print(resta)
print(Division)
print(Multiplicacion)
print(potencia)
print(f"Suma: {suma}")
print(f"Resta: {resta}")
print(f"Multiplicacion: {Multiplicacion}")
print(f"Division: {Division}")
print(f"Potencia: {potencia}")

a = 12# tipo de dato entero (int) 4 bites
b = 3 # Tipo de dato decimal se llaman flotantes (float) 8bites
suma = a + b
resta = a - b
Multiplicacion = a * b
Division = a / b
potencia = a ** b
print(suma)
print(resta)
print(Division)
print(Multiplicacion)
print(potencia)
print(f"Suma: {suma}")
print(f"Resta: {resta}")
print(f"Multiplicacion: {Multiplicacion}")
print(f"Division: {Division}")
print(f"Potencia: {potencia}")

print(" Te Amo"*3)

print(" Hola " + "Cómo vas "*4)

print((" Hola" + " Cómo vas")*4)

## Juego de Cajero Automático

print("¡¡ BIENVENIDO AL CAJERO MUNDIAL !!")
nombre = input("Ingrese su nombre: ")
edad = int(input("Ingrese su edad : "))
clave = input("Ingrese su clave: ")
print(f"Su Nombre: {nombre} Su edad: {edad} y la clave es: {clave}")

## Juego de Cajero Automático
# Antiguamente sin formato

print("¡¡ BIENVENIDO AL CAJERO MUNDIAL !!")
nombre = input("Ingrese su nombre: ")
edad = int(input("Ingrese su edad : "))
clave = input("Ingrese su clave: ")
print("su nombre es:",nombre, " su edad es: ", edad, " su clave es: ", clave)

"""LIBRERIAS"""

import math as m
Pi = m.pi

"""SENO Y COSENO"""

import math as m
Pi = m.pi
print(Pi)
print(m.sin(m.radians(90))) # Seno transformando los radianes en 180
print(m.cos(m.radians(0)))   # Coseno transformando los radianes
# esto es para sacar el seno y el coseno.

import math as m
Pi = m.pi
print(Pi)
print(m.sin(m.radians(180))) # Seno transformando los radianes en 180
print(m.cos(m.radians(90)))   # Coseno transformando los radianes
# esto es para sacar el seno y el coseno.

import math as m
Pi = m.pi
print(Pi)
print(m.sin(m.radians(45))) # Seno transformando los radianes en 180
print(m.cos(m.radians(0)))   # Coseno transformando los radianes
# esto es para sacar el seno y el coseno.

"""REDONDEAR NÚMEROS"""

# Para Redondeo de números  al cielo (ceil)  y al suelo (floor)
print(m.ceil(5.779)) #Redondea al entero maximo posible 6
print(m.floor(5.002)) #Redondea al entero mnimo posible  5 en este caso

# tambien otras constantes
print(m.pi) # Constante PI
print(m.e) # Constante Euler
print(m.fabs(-789)) # valor absoluto. Volver uno negativo en positivo
print(m.sqrt(49)) # Raíz cuadrada de un numero
print(m.pow(9, 2)) #para la potencia 9 elevado a 2
print(m.factorial(5)) # para factoriales multiplicacion consecutiva de números
# el factorial de 0 es 1 no existe factorial del 0
print(m.hypot(4,3)) # calcular la hipotenusa formula matemática
# numeros aleatorios enteros con random debemos importar la libreria

"""NUMEROS ALEATORIOS"""

## numeros aleatorios enteros con random debemos importar la libreria
import random
var1 = random.randint(1, 20) # Enteros aleatorios ENTEROS entre 1 y 20
print(var1)

"""SE PUEDE JUGAR CON LAS VARIABLES. PONGO EL NUMERO VARIABLE COMO POTENCIA DE 9 LINEA 6"""

# tambien otras constantes
print(Pi) # Constante PI
print(m.e) # Constante Euler
print(m.fabs(-789)) #valor absoluto
print(m.sqrt(49)) # Raíz cuadrada de un numero
print(m.pow(9, random.randint(1, 5))) #para la potencia
print(m.factorial(5)) # para factoriales multiplicacion consecutiva de números
# el factorial de 0 es 1 no existe factorial del 0
print(m.hypot(4,3)) # calcular la hipotenusa formula matemática H = √ a2 + b2

# Redondear decimales
round(4.56878,1)

"""CONDICIONAL PARA INGRESAR A DISCOTECA AL CUMPLIR 2 CONDICIONALES"""

nombre= input("Ingrese su nombre: ")
edad = int(input("Ingrese su edad: ")) # lo obligo a que sea entero
dinero = int(input("Cuanto dinero tienes: ")) # lo obligo a que sea entero

if(edad>=18):
    print(f"{nombre} pasaste el primer filtro de la edad")
else:
    print("Prohibido la entrada a menores de edad !!")
if(dinero>=50000):
    print(f"{nombre} Pasaste el filtro de dinero")
else:
    print("Debes pagar cover, no puedes ingresar")
if(edad>=18 and dinero>=50000):
    print("Bienvenido a la Discoteca")
else:
    print("No puedes ingresar")

nombre= input("Ingrese su nombre: ")
edad = int(input("Ingrese su edad: ")) # lo obligo a que sea entero
dinero = int(input("Cuanto dinero tienes: ")) # lo obligo a que sea entero

if(edad>=18):
    print(f"{nombre} pasaste el primer filtro de la edad")
else:
    print("Prohibido la entrada a menores de edad !!")
if(dinero>=50000):
    print(f"{nombre} Pasaste el filtro de dinero")
else:
    print("Debes pagar cover, no puedes ingresar")
if(edad>=18 and dinero>=50000):
    print("Bienvenido a la Discoteca")
else:
    print("No puedes ingresar")

nombre= input("Ingrese su nombre: ")
edad = int(input("Ingrese su edad: ")) # lo obligo a que sea entero
dinero = int(input("Cuanto dinero tienes: ")) # lo obligo a que sea entero

if(edad>=18):
    print(f"{nombre} pasaste el primer filtro de la edad")
else:
    print("Prohibido la entrada a menores de edad !!")
if(dinero>=50000):
    print(f"{nombre} Pasaste el filtro de dinero")
else:
    print("Debes pagar cover, no puedes ingresar")
if(edad>=18 and dinero>=50000):
    print("Bienvenido a la Discoteca")
else:
    print("No puedes ingresar")

nombre= input("Ingrese su nombre: ")
edad = int(input("Ingrese su edad: ")) # lo obligo a que sea entero
dinero = int(input("Cuanto dinero tienes: ")) # lo obligo a que sea entero

if(edad>=18):
    print(f"{nombre} pasaste el primer filtro de la edad")
else:
    print("Prohibido la entrada a menores de edad !!")
if(dinero>=50000):
    print(f"{nombre} Pasaste el filtro de dinero")
else:
    print("Debes pagar cover, no puedes ingresar")
if(edad>=18 and dinero>=50000):
    print("Bienvenido a la Discoteca")
else:
    print("No puedes ingresar")

"""REALIZAR UN ALGORITMO QUE NOS DIGA SI UN NUMERO ES PAR O IMPAR LINEA58 CONDICIONALES"""

## Realizar un algoritmo que nos diga, si un numero
## Es para o Impar


num = int(input("Ingrese un numero entero: "))
if (num % 2 == 0):
    print(f"El numero {num} es par")
else:
    print(f"El numero {num} es impar")

"""PARA SABER CUAL ES EL MAYOR DE 3 NÚMEROS"""

## Mayor de tres numeros
num1 = int(input("Ingrese un numero entero: "))
num2 = int(input("Ingrese un numero entero: "))
num3 = int(input("Ingrese un numero entero: "))

if (num1 > num2 and num1 > num3):
    print(f"El mayor es {num1}")
elif (num2 > num3):
    print(f"El mayor es {num2}")
else:
    print(f"El mayor es {num3}")

"""CONVERSION DE NOTAS"""

nota = float(input("Ingrese su nota: "))

if nota < 3:
    print("Estado reprobado!!")
elif nota >= 3 and nota <= 4.5:
    print("Estado Sobresalieten!!")
else:
    print("Su estado es excelente")

"""DESCUENTOS EN TIENDAS"""

compra = float(input("Ingrese el valor de la compra: "))
if compra > 100000:
    descuento = compra*20/100
    total = compra - descuento
    print(f"Debes pagar {total:.2f} COP")
else:
    print(f"Debes pagar {compra:.2f} COP")

"""CICLOS O BUCLES"""

##Ciclos o Bucles....
##Ciclo while -- Mientras
## El ciclo siempre va funcionar siempre y cuando, la condición sea verdadera

#Contador básico del 1 al 5

i = 1
while i <= 5:
    print(i)
    i = i + 1

#Contador básico del 5 al 1
i = 5
while i >= 1:
    print(i)
    i = i - 1

"""FORMA LARGA DE CALCULADORA CIENTÍFICA"""

b = 0
while b == 0:
    print("¡¡¡Bienvenido a la calculadora científica!!!")
    print("1. Suma")
    print("2. Resta")
    print("3. Multiplicar")
    print("4. Salir")
    a = int(input("Seleccione una opcion (1-4)): "))

    if a == 1:
        num1 = int(input("Ingrese un numero: "))
        num2 = int(input("Ingrese un numero: "))
        print(f"La suma es {num1 + num2}")
    elif a == 2:
        num1 = int(input("Ingrese un numero: ")) # Agregar input para num1 and num2
        num2 = int(input("Ingrese un numero: "))
        print(f"La resta es {num1 - num2}")
    elif a == 3:
        num1 = int(input("Ingrese un numero: ")) # Agregar input para num1 and num2
        num2 = int(input("Ingrese un numero: "))
        print(f"La multiplicacion es {num1 * num2}")
    elif a == 4:
        b = 1
    else:
        print("Ingrese una opcion valida, ingresó un número errado")

"""OTRA FORMA MAS FÁCIL DE CALCULADORA"""

### Menú de una calculadora ###

print("Bienvenido a la calculadora cientifica")
print("1. Suma")
print("2. Resta")
print("3. Multiplicacion")
print("4. Division")
print("5. Potencia")
print("6. Salir")

a = int(input("Seleccione una opcion (1-6)"))
if a == 1:
  num1 = int(input("Ingrese un numero: "))
  num2 = int(input("Ingrese un numero: "))
  print(f"La suma es {num1 + num2}")
elif a == 2:
  num1= int(input("Ingrese un numero: "))
  num2 = int(input("Ingrese un numero: "))
  print(f"La resta es {num1 - num2}")
elif a== 3:
  num1 = int(input("Ingrese un numero: "))
  num2 = int(input("Ingrese un numero: "))
  print(f"La multiplicacion es {num1 * num2}")
elif a == 4:
  num1 = int(input("Ingrese un numero: "))
  num2 = int(input("Ingrese un numero: "))
  if num2 != 0:
    print(f"La division es {num1 / num2}")
  else:
    print(f"No se puede dividir entre 0")
elif a == 5:
  num1 = int(input("Ingrese un numero: "))
  num2 = int(input("Ingrese un numero: "))
  print(f"La potencia es {num1 ** num2}")
elif a == 6:
  print("Adios")
else:
  print("IngresO un numero errado")

"""PIDIENDO A GEMINI UN CODIGO PARA CALCULADORA"""

import math as m

b = 0
while b == 0:
    print("\n¡¡¡Bienvenido a la calculadora científica!!!")
    print("1. Suma")
    print("2. Resta")
    print("3. Multiplicar")
    print("4. División")
    print("5. Potencia (num1 ^ num2)")
    print("6. Raíz Cuadrada")
    print("7. Seno (en grados)")
    print("8. Coseno (en grados)")
    print("9. Logaritmo natural (ln)")
    print("10. Factorial")
    print("11. Valor Absoluto")
    print("12. Salir")

    a = int(input("Seleccione una opción (1-12)): "))

    if a == 1:
        num1 = float(input("Ingrese el primer número: "))
        num2 = float(input("Ingrese el segundo número: "))
        print(f"La suma es {num1 + num2}")
    elif a == 2:
        num1 = float(input("Ingrese el primer número: "))
        num2 = float(input("Ingrese el segundo número: "))
        print(f"La resta es {num1 - num2}")
    elif a == 3:
        num1 = float(input("Ingrese el primer número: "))
        num2 = float(input("Ingrese el segundo número: "))
        print(f"La multiplicación es {num1 * num2}")
    elif a == 4:
        num1 = float(input("Ingrese el primer número: "))
        num2 = float(input("Ingrese el segundo número: "))
        if num2 != 0:
            print(f"La división es {num1 / num2}")
        else:
            print("Error: No se puede dividir por cero.")
    elif a == 5:
        num1 = float(input("Ingrese la base: "))
        num2 = float(input("Ingrese el exponente: "))
        print(f"La potencia es {m.pow(num1, num2)}")
    elif a == 6:
        num = float(input("Ingrese el número para la raíz cuadrada: "))
        if num >= 0:
            print(f"La raíz cuadrada es {m.sqrt(num)}")
        else:
            print("Error: No se puede calcular la raíz cuadrada de un número negativo.")
    elif a == 7:
        degrees = float(input("Ingrese el ángulo en grados para el seno: "))
        print(f"El seno de {degrees} grados es {m.sin(m.radians(degrees))}")
    elif a == 8:
        degrees = float(input("Ingrese el ángulo en grados para el coseno: "))
        print(f"El coseno de {degrees} grados es {m.cos(m.radians(degrees))}")
    elif a == 9:
        num = float(input("Ingrese el número para el logaritmo natural: "))
        if num > 0:
            print(f"El logaritmo natural de {num} es {m.log(num)}")
        else:
            print("Error: El logaritmo natural solo es para números positivos.")
    elif a == 10:
        num = int(input("Ingrese un número entero no negativo para el factorial: "))
        if num >= 0:
            print(f"El factorial de {num} es {m.factorial(num)}")
        else:
            print("Error: El factorial solo es para números enteros no negativos.")
    elif a == 11:
        num = float(input("Ingrese un número para obtener su valor absoluto: "))
        print(f"El valor absoluto de {num} es {m.fabs(num)}")
    elif a == 12:
        b = 1
        print("Saliendo de la calculadora. ¡Hasta luego!")
    else:
        print("Ingrese una opción válida (1-12).")

"""TABLA DE MULTIPLICAR. El 10 varía al que deseemos llegar la tabla"""

n = int(input("Ingrese el número del que desee conocer la tabla de multiplicar"))
i = 1

while i <= 13:
  print(f"{n} x {i} = {n*i}")
  i = i + 1

"""SI QUIERO SEGUIR PREGUNTANDO NUMEROS PARA NUEVAS TABLAS"""

while True:
  n = int(input("Ingrese el número del que desee conocer la tabla de multiplicar (o 0 para salir): "))
  if n == 0:
    print("Saliendo del generador de tablas.")
    break
  i = 1

  while i <= 13:
    print(f"{n} x {i} = {n*i}")
    i = i + 1

"""JUEGO DE ADIVINANZA"""

import random
numero_secreto = random.randint(1, 10)
intentos = 0
print ("Adivina un numero entre el 1 y el 10")

while True:
    numero = int(input("Ingrese un numero: "))
    intentos = intentos + 1
    if intentos != 5:
        if numero == numero_secreto:
            print("Felicidades adivinaste el numero!!!")
            break
        elif numero < numero_secreto:
            print("ingresa un numero mayor")
        else:
            print("ingresa un numero menor")
    else:
        print("Lo siento, PERDISTE !!!")
        break

PARA QUE ME DIGA EL NÚMERO SECRETO LO IMPRIMO EN LA ÚLTIMA LINEA

import random
numero_secreto = random.randint(1, 10)
intentos = 0
print ("Adivina un numero entre el 1 y el 10")

while True:
    numero = int(input("Ingrese un numero: "))
    intentos = intentos + 1
    if intentos != 5:
        if numero == numero_secreto:
            print("Felicidades adivinaste el numero!!!")
            break
        elif numero < numero_secreto:
            print("ingresa un numero mayor")
        else:
            print("ingresa un numero menor")
    else:
        print("Lo siento, PERDISTE !!!")
        break
numero_secreto

"""SIMULACION CARRITO DE COMPRAS"""

print ("¡Carro de compra!")
total = 0
while True:
    producto = input("Ingrese el nombre del producto o Salir para terminar: ")
    if producto.lower() == "salir":
        break
    else:
        precio = float(input(f"Ingrese el precio del {producto}: "))
        total = total + precio
print(f"El total a pagar es: {total:.2f} pesos")